export enum ActionTypes {
  CHANGE_FORM = 'CHANGE_FORM',
  CLEAR_FORM = 'CLEAR_FORM',
  FILTER_CHANGE = 'FILTER_CHANGE',
  CREATE_SERVICE_ITEM = 'CREATE_SERVICE_ITEM',
  UPDATE_SERVICE_ITEM = 'UPDATE_SERVICE_ITEM',
  DELETE_SERVICE_ITEM = 'DELETE_SERVICE_ITEM',
  OPEN_TO_UPDATE_SERVICE_ITEM = 'OPEN_TO_UPDATE_SERVICE_ITEM',
}
